In [5]:
import numpy as np
lst=[1,2,3,4,5]
print(lst)
arr=np.array(lst)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [2]:
a=range(6)
print(a)
for i in a:
    print(i)

range(0, 6)
0
1
2
3
4
5


In [3]:
a=np.arange(6)
print(a)
print(type(a))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
np.arange(0,15,4)

array([ 0,  4,  8, 12])

In [5]:
print(np.arange(0,15,2))

[ 0  2  4  6  8 10 12 14]


In [6]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3,3,1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(3,3,-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [15]:
np.eye(N=4,M=5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [16]:
# Create a 4x4 matrix with ones on the first upper diagonal
np.eye(N=4,M=4,k=1,dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [20]:
# Generate 5 evenly spaced numbers between 0 and 1 with float32 data type
np.linspace(0, 1, 5, dtype=np.float32)

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)

In [ ]:
#Generate 5 evenly spaced numbers between 0 and 2, and return the step size
arr,step=np.linspace(0,2,5,retstep=True)
print("Array:", arr)
print("Step size:", step)

Array: (array([0. , 0.5, 1. , 1.5, 2. ]), np.float64(0.5))
Step size: 0.5


In [26]:
print(np.log(10))

2.302585092994046


In [25]:
print(np.log10(10))

1.0


In [27]:
print(np.log(np.exp(5.2)))

5.2


In [30]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print(mat.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [33]:
vec4=np.linspace(0,5,10)
vec4

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [34]:
print(vec4.reshape(2,5))

[[0.         0.55555556 1.11111111 1.66666667 2.22222222]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]


In [35]:
print(vec4.reshape(10,1))

[[0.        ]
 [0.55555556]
 [1.11111111]
 [1.66666667]
 [2.22222222]
 [2.77777778]
 [3.33333333]
 [3.88888889]
 [4.44444444]
 [5.        ]]


In [37]:
vec5=np.arange(1,6)
vec6=np.arange(3,8)
print(vec5,vec6)

[1 2 3 4 5] [3 4 5 6 7]


In [38]:
print(vec5+vec6)

[ 4  6  8 10 12]


In [39]:
print(vec5-vec6)

[-2 -2 -2 -2 -2]


In [40]:
print(vec5/vec6)
print(1/vec6)

[0.33333333 0.5        0.6        0.66666667 0.71428571]
[0.33333333 0.25       0.2        0.16666667 0.14285714]


In [43]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[0,7]])
print(m1)
print(m2)

[[1 2]
 [3 4]]
[[5 6]
 [0 7]]


In [44]:
print(m1+m2)

[[ 6  8]
 [ 3 11]]


In [45]:
print(m1*m2)

[[ 5 12]
 [ 0 28]]


In [46]:
print(np.matmul(m1,m2))

[[ 5 20]
 [15 46]]


In [47]:
vec7=np.array(['red','blue','orange','pink','red'])
print(vec7)

['red' 'blue' 'orange' 'pink' 'red']


In [48]:
np.unique(vec7)

array(['blue', 'orange', 'pink', 'red'], dtype='<U6')

In [49]:
print(vec7=='red')
print(vec7[vec7!='red'])

[ True False False False  True]
['blue' 'orange' 'pink']


In [51]:
# Generate an array of random numbers from a uniform distribution
uniform_random=np.random.rand(3,3)
print(uniform_random)

[[0.27977672 0.24519753 0.10962906]
 [0.81506145 0.32011516 0.35711275]
 [0.54495954 0.32393905 0.40226302]]


In [52]:
# Generate an array of random numbers from a normal distribution
#Standard normal distribution (Gaussian distribution).
normal_random=np.random.randn(3,3)
print(normal_random)

[[ 0.91493987 -1.63288107  0.58778053]
 [ 1.65143104  0.31399181 -0.97694169]
 [ 0.51269582 -0.56771504  0.12711641]]


Uniform distribution (np.random.rand) Use when all values in a range are equally likely. Example: random guessing, shuffling, simulation where every outcome has same chance.

Normal distribution (np.random.randn, np.random.normal) Use when values cluster around a mean with fewer extremes (bell curve). Example: heights, test scores, sensor noise, many natural measurements.

In [54]:
#Generates random numbers with a mean of 0 and a standard deviation of 1.
standard_normal_random=np.random.randn(3,3)
print(standard_normal_random)

[[ 0.11475799  1.36005411 -0.36830204]
 [ 1.73278592 -0.84089648  0.69201806]
 [ 0.60094197  1.00696084 -1.50623884]]


np.random.rand: Generates random numbers from a uniform distribution. Values are in the range [0, 1). Example: np.random.rand(3, 3) generates a 3x3 array of random numbers between 0 and 1.

np.random.randn: Generates random numbers from a standard normal distribution. Values can range from negative infinity to positive infinity, but most values will be within a few standard deviations of the mean (0). Example: np.random.randn(3, 3) generates a 3x3 array of random numbers with a mean of 0 and a standard deviation of 1.

In [55]:
rand_mat=np.random.rand(3,5)
print(rand_mat)

[[0.29557012 0.79421717 0.24598697 0.54562632 0.07590991]
 [0.63327729 0.62024176 0.24682697 0.95027854 0.2143076 ]
 [0.55714551 0.83410578 0.85342178 0.31467364 0.10864976]]


In [56]:
print(rand_mat[0])

[0.29557012 0.79421717 0.24598697 0.54562632 0.07590991]


In [58]:
print(rand_mat[0][0])
print(rand_mat[0,0])

0.29557012338950905
0.29557012338950905


In [59]:
print(rand_mat[0:2, 2:4])

[[0.24598697 0.54562632]
 [0.24682697 0.95027854]]


In [60]:
rand_vec=np.random.randn(10)
print(rand_vec)

[-0.16846363  0.52704485 -1.77009438  0.66145224  0.59467448  0.56074572
 -0.56679438 -0.76754084 -1.54584177 -0.52501298]


In [61]:
print(rand_vec>0)

[False  True False  True  True  True False False False False]


In [62]:
print(rand_vec[rand_vec>0])

[0.52704485 0.66145224 0.59467448 0.56074572]


In [63]:
rand_mat=np.random.rand(3,5)
print(rand_mat)

[[0.04543556 0.81126189 0.85061479 0.49107385 0.65001289]
 [0.87400981 0.91976396 0.41578764 0.30385596 0.51566924]
 [0.34199167 0.25119802 0.15901793 0.0145629  0.79196954]]


In [64]:
sub_mat=rand_mat[0:2,0:2]
print(sub_mat)

[[0.04543556 0.81126189]
 [0.87400981 0.91976396]]


In [66]:
sub_mat[:]=4
print(sub_mat)

[[4. 4.]
 [4. 4.]]


In [67]:
print(rand_mat)

[[4.         4.         0.85061479 0.49107385 0.65001289]
 [4.         4.         0.41578764 0.30385596 0.51566924]
 [0.34199167 0.25119802 0.15901793 0.0145629  0.79196954]]


NumPy slicing → VIEW

If you want independent copy:sub_mat = rand_mat[0:2, 0:2].copy()

In [72]:
rand_mat=np.random.rand(3,5)
print(rand_mat)

[[0.4357126  0.57562328 0.30933215 0.41069491 0.86928575]
 [0.95175557 0.38571527 0.77029752 0.39080674 0.15592926]
 [0.70415428 0.08948819 0.4596354  0.65035423 0.07240248]]


In [70]:
sub_mat1=rand_mat[0:2,0:2].copy()
sub_mat1[:]=6
print(sub_mat1)

[[6. 6.]
 [6. 6.]]


In [71]:
print(rand_mat)

[[0.41668295 0.76121816 0.83851989 0.28589135 0.26356724]
 [0.53117856 0.75512555 0.75229608 0.11134437 0.53657871]
 [0.23577819 0.46567594 0.13758319 0.86589626 0.82746972]]


In [73]:
ranarr=np.random.randint(1,50,5)
print(ranarr)

[39 41 41 49 43]


In [74]:
ranarr=np.random.randint(1,50)
print(ranarr)

23


Statistical Functions np.mean: Compute the mean of the array. np.median: Compute the median of the array. np.std: Compute the standard deviation of the array. np.var: Compute the variance of the array. np.sum: Compute the sum of the array

In [ ]:
data = np.array([1,2,3,4,5])
#mean
mean=np.mean(data)
print(mean)
#median
median=np.median(data)
print(median)
#standard deviation
std_dev=np.std(data)
print(std_dev)
#variance
variance=np.var(data)
print(variance)
#sum
total_sum=np.sum(data)
print(total_sum)

3.0
3.0
1.4142135623730951
2.0
15


In [76]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [77]:
np.transpose(arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
np.random.seed(4)
rand_mat=np.random.rand(2,3)    #controlling randomness
print(rand_mat)

[[0.96702984 0.54723225 0.97268436]
 [0.71481599 0.69772882 0.2160895 ]]


In [79]:
np.random.seed(42)
rand_mat=np.random.rand(2,3)    #controlling randomness
print(rand_mat)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


/Pandas

In [6]:
import pandas as pd

In [81]:
labels=['a','b','c']
my_list=[10,20,30]
print(my_list)
pd.Series(data=my_list)

[10, 20, 30]


0    10
1    20
2    30
dtype: int64

In [82]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [83]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [84]:
d={'a':10,'b':20,'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [85]:
arr=np.array([40,50,60])
pd.Series(arr)

0    40
1    50
2    60
dtype: int64

In [86]:
ser1=pd.Series([10,20,30,40,50],index=['India','USA','Japan','Russia','Sri Lanka'])
print(ser1)

India        10
USA          20
Japan        30
Russia       40
Sri Lanka    50
dtype: int64


In [87]:
ser2=pd.Series([10,20,50,60],index=['India','Germany','Japan','Russia'])
ser2

India      10
Germany    20
Japan      50
Russia     60
dtype: int64

In [88]:
ser1+ser2

Germany        NaN
India         20.0
Japan         80.0
Russia       100.0
Sri Lanka      NaN
USA            NaN
dtype: float64

In [89]:
ser1[:]==10

India         True
USA          False
Japan        False
Russia       False
Sri Lanka    False
dtype: bool

In [90]:
ser1[ser1[:]==10]

India    10
dtype: int64

In [91]:
ser1[ser1[:]>10]

USA          20
Japan        30
Russia       40
Sri Lanka    50
dtype: int64

In [92]:
fun=pd.Series([sum,print,len])
print(fun)

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object


In [93]:
print("hi")
fun[1]("hi")

hi
hi


In [94]:
ser=pd.Series([1,2,3,4])
ser

0    1
1    2
2    3
3    4
dtype: int64

DataFrame

In [96]:
dfr=pd.DataFrame([1,2,3,4])
dfr

,0
0,1
1,2
2,3
3,4


In [97]:
dfr=pd.DataFrame([1,2,3,4],['a','b','c','d'])
dfr

,0
a,1
b,2
c,3
d,4


In [98]:
dfr=pd.DataFrame([1,2,3,4],['a','b','c','d'],columns=['x'])
dfr

,x
a,1
b,2
c,3
d,4


In [99]:
dfr=pd.DataFrame([[1,2],[3,4]],index=['a','b'],columns=['x','y'])
dfr

,x,y
a,1,2
b,3,4


In [8]:
from numpy.random import randn
dfr=pd.DataFrame(randn(4,4),index=['a','b','c','d'],columns=['w','x','y','z'])
dfr

,w,x,y,z
a,0.474303,-0.300979,0.554936,0.935859
b,1.032230,1.324636,1.674069,0.019669
c,-0.274329,0.828443,-0.581722,-0.261309
d,-0.739175,-0.476775,-0.352312,1.001785


In [7]:
dic={"Player":["Virat","Rohit","Dhoni"],"Score":[100,150,200]}
ser=pd.Series(dic)
ser

Player    [Virat, Rohit, Dhoni]
Score           [100, 150, 200]
dtype: object

In [8]:
dic={"Player":["Virat","Rohit","Dhoni"],"Score":[100,150,200]}
dfr2=pd.DataFrame(dic)
dfr2

,Player,Score
0,Virat,100
1,Rohit,150
2,Dhoni,200


In [10]:
print(type(dfr2))
print(type(dfr2['Player']))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>


In [11]:
lst='A B C D'.split()
print(lst)

['A', 'B', 'C', 'D']


In [3]:
lst='A B C D'.split(",")
print(lst)

['A B C D']


In [30]:
dfr=pd.DataFrame(randn(4,4),index='A B C D'.split(),columns='W X Y Z'.split())
dfr

,W,X,Y,Z
A,0.888376,0.773539,-1.635500,-0.482913
B,0.222503,0.949496,-0.297431,-0.452657
C,-1.367373,-1.031459,0.488364,0.342091
D,0.365683,-0.226127,1.870792,1.617723


In [11]:
dfr['W']

A    0.316205
B    2.450521
C    0.673308
D   -0.288017
Name: W, dtype: float64

In [12]:
dfr[['W','X']]

,W,X
A,0.316205,-0.723162
B,2.450521,-0.036725
C,0.673308,-0.705613
D,-0.288017,1.370632


In [13]:
dfr.loc['A']

W    0.316205
X   -0.723162
Y    0.587908
Z    1.335290
Name: A, dtype: float64

In [14]:
dfr.iloc[1]

W    2.450521
X   -0.036725
Y    0.700565
Z   -0.145656
Name: B, dtype: float64

In [21]:
dfr['new']=dfr['W']+dfr['Y']
dfr

,W,X,Y,Z,new
A,0.316205,-0.723162,0.587908,1.335290,0.904113
B,2.450521,-0.036725,0.700565,-0.145656,3.151086
C,0.673308,-0.705613,0.061034,0.602797,0.734342
D,-0.288017,1.370632,-0.664264,0.687596,-0.952282


In [16]:
dfr1=dfr.drop('new',axis=1,inplace=False)
dfr1

,W,X,Y,Z
A,0.316205,-0.723162,0.587908,1.335290
B,2.450521,-0.036725,0.700565,-0.145656
C,0.673308,-0.705613,0.061034,0.602797
D,-0.288017,1.370632,-0.664264,0.687596


In [22]:
dfr

,W,X,Y,Z,new
A,0.316205,-0.723162,0.587908,1.335290,0.904113
B,2.450521,-0.036725,0.700565,-0.145656,3.151086
C,0.673308,-0.705613,0.061034,0.602797,0.734342
D,-0.288017,1.370632,-0.664264,0.687596,-0.952282


In [23]:
dfr1=dfr.drop('new',axis=1,inplace=True)
print(dfr1)

None


In [24]:
dfr

,W,X,Y,Z
A,0.316205,-0.723162,0.587908,1.335290
B,2.450521,-0.036725,0.700565,-0.145656
C,0.673308,-0.705613,0.061034,0.602797
D,-0.288017,1.370632,-0.664264,0.687596


In [25]:
dfr.drop('D',axis=0)

,W,X,Y,Z
A,0.316205,-0.723162,0.587908,1.335290
B,2.450521,-0.036725,0.700565,-0.145656
C,0.673308,-0.705613,0.061034,0.602797


In [26]:
dfr

,W,X,Y,Z
A,0.316205,-0.723162,0.587908,1.335290
B,2.450521,-0.036725,0.700565,-0.145656
C,0.673308,-0.705613,0.061034,0.602797
D,-0.288017,1.370632,-0.664264,0.687596


In [27]:
dfr.loc[['A','B'],['W','Y']]

,W,Y
A,0.316205,0.587908
B,2.450521,0.700565


In [28]:
dfr>0

,W,X,Y,Z
A,True,False,True,True
B,True,False,True,False
C,True,False,True,True
D,False,True,False,True


In [31]:
dfr[dfr>0]

,W,X,Y,Z
A,0.888376,0.773539,NaN,NaN
B,0.222503,0.949496,NaN,NaN
C,NaN,NaN,0.488364,0.342091
D,0.365683,NaN,1.870792,1.617723


In [32]:
dfr[dfr['W']>0]

,W,X,Y,Z
A,0.888376,0.773539,-1.635500,-0.482913
B,0.222503,0.949496,-0.297431,-0.452657
D,0.365683,-0.226127,1.870792,1.617723


seed function is used to save the state of a random function, so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines (for a specific seed value)

In [33]:
np.random.seed(4)
dfr=pd.DataFrame(randn(4,4),index=['a','b','c','d'],columns=['w','x','y','z'])
dfr

,w,x,y,z
a,0.050562,0.499951,-0.995909,0.693599
b,-0.418302,-1.584577,-0.647707,0.598575
c,0.332250,-1.147477,0.618670,-0.087987
d,0.425072,0.332253,-1.156816,0.350997


In [34]:
dfr[dfr['w']>0]

,w,x,y,z
a,0.050562,0.499951,-0.995909,0.693599
c,0.332250,-1.147477,0.618670,-0.087987
d,0.425072,0.332253,-1.156816,0.350997


In [35]:
dfr[(dfr['w']>0) & (dfr['y']>0)]

,w,x,y,z
c,0.33225,-1.147477,0.61867,-0.087987


In [36]:
dfr

,w,x,y,z
a,0.050562,0.499951,-0.995909,0.693599
b,-0.418302,-1.584577,-0.647707,0.598575
c,0.332250,-1.147477,0.618670,-0.087987
d,0.425072,0.332253,-1.156816,0.350997


In [37]:
newind='KA KE TN AP'.split()
newind

['KA', 'KE', 'TN', 'AP']

In [41]:
dfr['States']=newind
dfr

,w,x,y,z,States
States,,,,,
KA,0.050562,0.499951,-0.995909,0.693599,KA
KE,-0.418302,-1.584577,-0.647707,0.598575,KE
TN,0.332250,-1.147477,0.618670,-0.087987,TN
AP,0.425072,0.332253,-1.156816,0.350997,AP


In [42]:
dfr.set_index('States',inplace=True)
dfr

,w,x,y,z
States,,,,
KA,0.050562,0.499951,-0.995909,0.693599
KE,-0.418302,-1.584577,-0.647707,0.598575
TN,0.332250,-1.147477,0.618670,-0.087987
AP,0.425072,0.332253,-1.156816,0.350997


In [43]:
data={'A':[1,2,3],'B':[4,5,6]}
df=pd.DataFrame(data)
df

,A,B
0,1,4
1,2,5
2,3,6


In [44]:
data={'A':[1,2,3],'B':[4,5,6]}
df=pd.DataFrame(data)
df.index.name='S no'
df

,A,B
S no,,
0,1,4
1,2,5
2,3,6


Multi-index and Groupby are very important concepts of data manipulation.

Multi-index allows you to represent data with multi-levels of indexing, creating a hierarchy in rows and columns.

Groupby lets you create groups of similar data and apply aggregate functions (e.g., mean, sum, count, standard deviation) to each group, condensing large datasets into meaningful summaries.

In [45]:
a=("Sachin","Ganguly","Dravid")
b=("Mumbai","Kolkata","Bangalore")
x=zip(a,b)
list(x)

[('Sachin', 'Mumbai'), ('Ganguly', 'Kolkata'), ('Dravid', 'Bangalore')]

In [46]:
#Creating the Tuple
tuples1 = [(30,'Larry'),(20,'Mike'),(18,'David'),(25,'Tim')]
print(tuples1)

[(30, 'Larry'), (20, 'Mike'), (18, 'David'), (25, 'Tim')]


In [47]:
midx=pd.MultiIndex.from_tuples(tuples1)
midx

MultiIndex([(30, 'Larry'),
            (20,  'Mike'),
            (18, 'David'),
            (25,   'Tim')],
           )

In [ ]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]